"""Tambah status aktif pada pengguna

Revision ID: 845665f64f65
Revises: 2b620584ca6a
Create Date: 2026-09-17 16:21:37.549820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845665f64f65'
down_revision = '2b620584ca6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
