"""Perbaikan nullable waktu penggunaan OTP

Revision ID: c27d1323ae2d
Revises: 9aba72b066b2
Create Date: 2026-09-18 13:52:56.153136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c27d1323ae2d'
down_revision = '9aba72b066b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_otp', schema=None) as batch_op:
        batch_op.alter_column('used_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_otp', schema=None) as batch_op:
        batch_op.alter_column('used_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
